apiVersion: v1
kind: Service
metadata:
  name: {{ include "consumer.fullname" . }}
  labels:
    {{- include "consumer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "consumer.selectorLabels" . | nindent 4 }}
